name: Production Build

on:
  push:
    branches:
      - main

jobs:
  deploy-to-production:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm

      # Setup Expo
      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          expo-cache: true
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Configure EAS Build
      - name: Configure EAS Build
        run: eas build:configure --platform android
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      # Trigger EAS Build for Android
      - name: Trigger EAS Build for Android
        run: |
          eas build --platform android --profile production --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
