name: Development Build

on:
  pull_request:
    branches:
      - develop

jobs:
  development-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      # Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm

      # Setup Expo
      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          expo-cache: true
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      # Install dependencies
      - name: Install dependencies
        run:
          npm ci
          # Run Jest tests
      - name: Run tests with Jest
        run: npm test -- --ci --coverage

      # Upload Jest test results
      - name: Upload Jest test results
        uses: actions/upload-artifact@v4
        with:
          name: jest-results
          path: coverage

      # Publish to EAS Update
      - name: Publish to EAS Update
        run: |
          BRANCH_NAME=build-${{ github.event.number }}
          eas update --branch $BRANCH_NAME --non-interactive --message "Development #${{ github.event.number }}"

      # Add EAS Update Link to PR
      - name: Add EAS Update Link to Development
        uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            ## Test this Development with EAS Update
            ![Expo QR](https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=exp://u.expo.dev/${{ secrets.EXPO_ACCOUNT_NAME }}/vifin-app?channel-name=build-${{ github.event.number }})
            **------ Build published to [EAS Update](https://expo.dev/accounts/${{ secrets.EXPO_ACCOUNT_NAME }}/projects/vifin-app/branches/build-${{ github.event.number }}) ------**
